# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Nagui Pinetta
# Description of the Site
description: Tech Writer - UX Writer - Product Manager
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://cdn.iconscout.com/icon/premium/png-512-thumb/t-rex-6209413-5427472.png?f=avif&w=256

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: naguipinetta@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: https://www.linkedin.com/in/jonathan-demian-pinetta/
github_username:  NaguiPinetta
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: G-J0NKP19PLY

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: TheDevsLot
# URL for the Image of the Author
author-image: https://i.ibb.co/6tMw1d6/images-prof-pic.png
# 60 Words About the Author
author-about: As an experienced technical writer with over six years in the field, I bring a wealth of expertise to the table. Originally from Argentina and currently located in Germany, I have worked extensively in the industry, with a diverse range of technical writing samples in my portfolio. From online help systems to knowledge bases, I have created various materials throughout my career. This page offers an overview of my recent technical writing projects, showcasing samples specifically tailored for this website. Feel free to explore the links to view the samples and get a glimpse of my work.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
